version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate AMI
          command: packer validate ./ami6.json
      - run:
          name: print all the env variables 
          command: |
            printenv
      
  build-base:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build AMI
          command: packer build ./ami6.json
          no_output_timeout: 30m
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
      